### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by Groctel** [jared-hughes/isosurfaces#1]
Hi!

I'm adding your package to the [AUR](https://wiki.archlinux.org/title/Arch_User_Repository) because it has recently became a dependency for [manim](https://aur.archlinux.org/packages/manim/). I see that you're not distributing the package under any license, so I'm writing this issue to let you know of that fact and asking that you please inform me if you ever add it so that I can update the package asap :)

**Comment by jared-hughes** [comment]
Hello; I have added a license.

**Comment by Eloitor** [comment]
Hi, I'm packaging manim for void linux, and the license file is not in the tar.gz... Could you make a new release with the license file included?

Thanks!

**Comment by jared-hughes** [comment]
Sure, I should do a new release anyways due to some bugfixes. I'll see if I have time this weekend.

**Comment by jared-hughes** [comment]
Alright, the release is out (v0.1.1), and I checked to make sure the LICENSE was in the .tar.gz
